### PR TITLE
chore: c1 get event accepts CID now

### PR DESCRIPTION
**Pull request by dav1do**
This change is made in order to stay compatible with the [new ceramic one api](https://github.com/ceramicnetwork/rust-ceramic/pull/327), where we accept CID instead of EventID. The recon input and output are now different, so I created a second interface to help get the create/assert right.

I made some adjustments to events and we now build a valid ceramic deterministic event so that recon can parse and sync it. I used the unique field of a deterministic event to avoid signing and make sure they were different so that recon would sync each of them.

### CODE REVIEW

**Review by stbrody — APPROVED** [review]
lgtm, though we'll also want to update the above test once it's also been updated to use a real event instead of a fake one

**Comment by dav1do** [comment]
> lgtm, though we'll also want to update the above test once it's also been updated to use a real event instead of a fake one

yeah, the test above is still skipped, along with the entire recon-sync file. I'm not sure we really need these tests or if we should just re-write them in terms of the MID sync and let js-ceramic handle talking to c1.

**Comment by stbrody** [comment]
well, js-ceramic doesn't ever call GET on the events endpoint.  Pretty sure that endpoint is for our own testing purposes only right now, so without some explicit test of it it won't have any coverage at all

**Comment by dav1do** [comment]
> well, js-ceramic doesn't ever call GET on the events endpoint. Pretty sure that endpoint is for our own testing purposes only right now, so without some explicit test of it it won't have any coverage at all

huh, true. I was thinking we used it after we got IDs from the feed.. but I guess we get it from the the kubo rpc still. 

The skipped tests all use the POST endpoint, which would be covered going through js-ceramic/MIDs. I'm not 100% convinced there's value simulating explicit sync scenarios here through (at least through the recon API unless we only do it in hermetic envs)... it seems better to use MIDs and set up whatever scenarios we want in general (and especially for durable envs).

**Review by nathanielc — APPROVED** [review]

**Review by nathanielc — APPROVED** [review]

**Pull request merged**
